In [3]:
import numpy as np
import pandas as pd

In [17]:
covid_sp = pd.read_csv('/content/drive/MyDrive/analise_dados/aula3/arquivos/dados_covid_sp.csv',sep=";", encoding='utf-8')
covid_sp

,nome_munic,codigo_ibge,dia,mes,datahora,casos,casos_novos,casos_pc,casos_mm7d,obitos,...,nome_drs,cod_drs,pop,pop_60,area,map_leg,map_leg_s,latitude,longitude,semana_epidem
0,Adamantina,3500105,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,...,Marília,5,33894,7398,41199,0,8.0,"-21,6820","-51,0737",9
1,Adolfo,3500204,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,...,São José do Rio Preto,15,3447,761,21106,0,8.0,"-21,2325","-49,6451",9
2,Aguaí,3500303,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,...,São João da Boa Vista,14,35608,5245,47455,0,8.0,"-22,0572","-46,9735",9
3,Águas da Prata,3500402,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,...,São João da Boa Vista,14,7797,1729,14267,0,8.0,"-21,9319","-46,7176",9
4,Águas de Lindóia,3500501,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,...,Campinas,3,18374,3275,6013,0,8.0,"-22,4733","-46,6314",9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374029,Ignorado,9999999,21,9,2021-09-21,1956,-477,"0,00000000000000e+00","-931,428571428571445",7,...,NaN,0,0,0,0,NaN,NaN,"0,0000","0,0000",38
374030,Ignorado,9999999,22,9,2021-09-22,1414,-542,"0,00000000000000e+00","-1038,714285714285779",7,...,NaN,0,0,0,0,NaN,NaN,"0,0000","0,0000",38
374031,Ignorado,9999999,23,9,2021-09-23,962,-452,"0,00000000000000e+00","-348,000000000000000",6,...,NaN,0,0,0,0,NaN,NaN,"0,0000","0,0000",38
374032,Ignorado,9999999,24,9,2021-09-24,557,-405,"0,00000000000000e+00","-774,428571428571445",1,...,NaN,0,0,0,0,NaN,NaN,"0,0000","0,0000",38
374033,Ignorado,9999999,25,9,2021-09-25,128,-429,"0,00000000000000e+00","-472,142857142857167",0,...,NaN,0,0,0,0,NaN,NaN,"0,0000","0,0000",38

In [12]:
covid_sp.rename(columns={'nome_munic':'cidade'},inplace = True)
covid_sp

,cidade,codigo_ibge,dia,mes,datahora,casos,casos_novos,casos_pc,casos_mm7d,obitos,...,nome_drs,cod_drs,pop,pop_60,area,map_leg,map_leg_s,latitude,longitude,semana_epidem
0,Adamantina,3500105,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,...,Marília,5,33894,7398,41199,0,8.0,"-21,6820","-51,0737",9
1,Adolfo,3500204,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,...,São José do Rio Preto,15,3447,761,21106,0,8.0,"-21,2325","-49,6451",9
2,Aguaí,3500303,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,...,São João da Boa Vista,14,35608,5245,47455,0,8.0,"-22,0572","-46,9735",9
3,Águas da Prata,3500402,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,...,São João da Boa Vista,14,7797,1729,14267,0,8.0,"-21,9319","-46,7176",9
4,Águas de Lindóia,3500501,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,...,Campinas,3,18374,3275,6013,0,8.0,"-22,4733","-46,6314",9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374029,Ignorado,9999999,21,9,2021-09-21,1956,-477,"0,00000000000000e+00","-931,428571428571445",7,...,NaN,0,0,0,0,NaN,NaN,"0,0000","0,0000",38
374030,Ignorado,9999999,22,9,2021-09-22,1414,-542,"0,00000000000000e+00","-1038,714285714285779",7,...,NaN,0,0,0,0,NaN,NaN,"0,0000","0,0000",38
374031,Ignorado,9999999,23,9,2021-09-23,962,-452,"0,00000000000000e+00","-348,000000000000000",6,...,NaN,0,0,0,0,NaN,NaN,"0,0000","0,0000",38
374032,Ignorado,9999999,24,9,2021-09-24,557,-405,"0,00000000000000e+00","-774,428571428571445",1,...,NaN,0,0,0,0,NaN,NaN,"0,0000","0,0000",38
374033,Ignorado,9999999,25,9,2021-09-25,128,-429,"0,00000000000000e+00","-472,142857142857167",0,...,NaN,0,0,0,0,NaN,NaN,"0,0000","0,0000",38

In [18]:
covid_sp.drop(columns=['codigo_ibge'],inplace = True)
covid_sp.shape

(374034, 25)

In [19]:
covid_sp = covid_sp.drop(covid_sp.index[[1,2,3]])

In [20]:
covid_sp.head(10)

,nome_munic,dia,mes,datahora,casos,casos_novos,casos_pc,casos_mm7d,obitos,obitos_novos,...,nome_drs,cod_drs,pop,pop_60,area,map_leg,map_leg_s,latitude,longitude,semana_epidem
0,Adamantina,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,...,Marília,5,33894,7398,41199,0,8.0,"-21,6820","-51,0737",9
4,Águas de Lindóia,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,...,Campinas,3,18374,3275,6013,0,8.0,"-22,4733","-46,6314",9
5,Águas de Santa Bárbara,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,...,Bauru,12,5931,1106,40446,0,8.0,"-22,8812","-49,2421",9
6,Águas de São Pedro,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,...,Piracicaba,11,3122,764,361,0,8.0,"-22,5977","-47,8734",9
7,Agudos,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,...,Bauru,12,36134,5524,96671,0,8.0,"-22,4694","-48,9863",9
8,Alambari,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,...,Sorocaba,6,5779,830,1596,0,8.0,"-23,5503","-47,8980",9
9,Alfredo Marcondes,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,...,Presidente Prudente,2,3927,907,11892,0,8.0,"-21,9527","-51,4140",9
10,Altair,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,...,Barretos,16,4036,552,31301,0,8.0,"-20,5242","-49,0571",9
11,Altinópolis,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,...,Ribeirão Preto,1,15553,2980,92896,0,8.0,"-21,0214","-47,3712",9
12,Alto Alegre,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,...,Araçatuba,7,4017,964,31857,0,8.0,"-21,5811","-50,1680",9

In [22]:
covid_sp = covid_sp.reset_index(drop=True)
covid_sp

,nome_munic,dia,mes,datahora,casos,casos_novos,casos_pc,casos_mm7d,obitos,obitos_novos,...,nome_drs,cod_drs,pop,pop_60,area,map_leg,map_leg_s,latitude,longitude,semana_epidem
0,Adamantina,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,...,Marília,5,33894,7398,41199,0,8.0,"-21,6820","-51,0737",9
1,Águas de Lindóia,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,...,Campinas,3,18374,3275,6013,0,8.0,"-22,4733","-46,6314",9
2,Águas de Santa Bárbara,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,...,Bauru,12,5931,1106,40446,0,8.0,"-22,8812","-49,2421",9
3,Águas de São Pedro,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,...,Piracicaba,11,3122,764,361,0,8.0,"-22,5977","-47,8734",9
4,Agudos,25,2,2020-02-25,0,0,"0,00000000000000e+00","0,000000000000000",0,0,...,Bauru,12,36134,5524,96671,0,8.0,"-22,4694","-48,9863",9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
374026,Ignorado,21,9,2021-09-21,1956,-477,"0,00000000000000e+00","-931,428571428571445",7,-1,...,NaN,0,0,0,0,NaN,NaN,"0,0000","0,0000",38
374027,Ignorado,22,9,2021-09-22,1414,-542,"0,00000000000000e+00","-1038,714285714285779",7,0,...,NaN,0,0,0,0,NaN,NaN,"0,0000","0,0000",38
374028,Ignorado,23,9,2021-09-23,962,-452,"0,00000000000000e+00","-348,000000000000000",6,-1,...,NaN,0,0,0,0,NaN,NaN,"0,0000","0,0000",38
374029,Ignorado,24,9,2021-09-24,557,-405,"0,00000000000000e+00","-774,428571428571445",1,-5,...,NaN,0,0,0,0,NaN,NaN,"0,0000","0,0000",38
374030,Ignorado,25,9,2021-09-25,128,-429,"0,00000000000000e+00","-472,142857142857167",0,-1,...,NaN,0,0,0,0,NaN,NaN,"0,0000","0,0000",38

In [27]:
covid_sp = covid_sp.loc[covid_sp.cidade == 'Ignorado']

AttributeError: ignored